# This file exists within 'dob':
#
#   https://github.com/hotoffthehamster/dob

# Travis CI config.
#
#   https://travis-ci.org/hotoffthehamster/dob

language: python

# Specify xenial for 3.7 support.
dist: xenial

matrix:
  include:
    # Unit tests run on each Python version.
    - env: TOXENV=py37
      python: '3.7'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=py35
      python: '3.5'
    # Other tasks run against latest Python.
    # - Upload reports to Codecov.io.
    - env: TOXENV=codecov
      python: '3.7'
    # - Verify long description (README.rst) will render on PyPI.
    - env: TOXENV=dist_check
      python: '3.7'
    # - Lint docs (doc8).
    - env: TOXENV=docs
      python: '3.7'
    # - Lint code (flake8).
    - env: TOXENV=flake8
      python: '3.7'
    # FIXME/2020-01-24: Add pep257 check -- once docstrings fixed.
    # # - Verify docstring conventions.
    # - env: TOXENV=pep257
    #   python: '3.7'

install:
  - pip install -U tox

script: tox

notifications:
  email: false

