# This file exists within 'dob':
#
#   https://github.com/hotoffthehamster/dob

# Travis CI config.
#
#   https://travis-ci.org/hotoffthehamster/dob

language: python

# Specify xenial or bionic for 3.7+ support.
dist: xenial

matrix:
  include:
    # Unit tests run on each Python version.
    - env: TOXENV=py38
      python: '3.8'
    - env: TOXENV=py37
      python: '3.7'
    - env: TOXENV=py36
      python: '3.6'
    # Other tasks run against latest Python.
    # - Upload reports to Codecov.io.
    - env: TOXENV=codecov
      python: '3.8'
    # - Verify long description (README.rst) will render on PyPI.
    - env: TOXENV=dist_check
      python: '3.8'
    # - Lint docs (doc8).
    - env: TOXENV=docs
      python: '3.8'
    # - Lint code (flake8).
    - env: TOXENV=flake8
      python: '3.8'
    # Unless docstrings repaired, linting disabled.
    #  # - Verify docstring conventions (n√©e pep257).
    #  - env: TOXENV=pydocstyle
    #    python: '3.8'

install:
  - pip install -U tox

script: tox

notifications:
  email: false

