# This file exists within 'dob':
#
#   https://github.com/hotoffthehamster/dob

# Travis CI config.
#
#   https://travis-ci.org/hotoffthehamster/dob

language: python

# Specify xenial for 3.7 support.
dist: xenial

matrix:
  include:
    # Unit tests run on each Python version.
    - env: TOXENV=py37
      python: '3.7'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=py35
      python: '3.5'
    # Other tasks run against latest Python.
    - env: TOXENV=codecov
      python: '3.7'
    - env: TOXENV=dist_check
      python: '3.7'
    - env: TOXENV=docs
      python: '3.7'
    - env: TOXENV=flake8
      python: '3.7'

install:
  - pip install -U tox

script: tox

notifications:
  email: false

